export {Home} from "./Home/Home"
export {Login,} from "./Authentication/Login"
export {Signup} from "./Authentication/Signup"
export {Authenticate} from "./Authentication/Authenticate"
export {useAuth, authReducer} from "./Authentication/authSlice"
export {usePost, postReducer,allPosts} from "./Post/postSlice"