import { v4 as uuid } from "uuid";
import { formatDate } from "../utils/authUtils";
/**
 * User Database can be added here.
 * You can add default users of your wish with different attributes
 * */

export const users = [
    {
    _id: uuid(),
    firstName : "Anup",
    lastName : "Gurung",
    username: "anupkmr",
    profileImg : "https://raw.githubusercontent.com/anupkgurung/images/main/social/anup.jpg",
    password: "akg123",
    bio : "hey there i am Anup",
    portfolio : "https://github.com/anupkgurung",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName : "Ajay",
    lastName : "kamta",
    username: "kamtaajay",
    profileImg : "https://raw.githubusercontent.com/anupkgurung/images/main/social/kamtaajay.jpg",
    password: "ak123",
    bio : "hey there i am Ajay",
    portfolio : "https://github.com/anupkgurung",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName : "Praveen",
    lastName : "Rawat",
    username: "praveenrawat",
    profileImg : "https://raw.githubusercontent.com/anupkgurung/images/main/social/praveenrawat.jpg",
    password: "pr123",
    bio : "hey there i am Praveen",
    portfolio : "https://github.com/impraveen",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName : "Vinay",
    lastName : "Goswami",
    username: "vinaygoswami",
    profileImg : "https://raw.githubusercontent.com/anupkgurung/images/main/social/vinay.jpg",
    password: "vg123",
    bio : "hey there i am Vinay",
    portfolio : "https://github.com/anupkgurung",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
  {
    _id: uuid(),
    firstName : "Prafful",
    lastName : "dhasmana",
    username: "pdhasmana",
    profileImg : "https://raw.githubusercontent.com/anupkgurung/images/main/social/prafful.jpg",
    password: "pd123",
    bio : "hey there i am Praff",
    portfolio : "https://github.com/anupkgurung",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
   {
    _id: uuid(),
    firstName : "Ayush",
    lastName : "Gurung",
    username: "ayushgurung",
    profileImg : "https://raw.githubusercontent.com/anupkgurung/images/main/social/ayush.jpg",
    password: "ag123",
    bio : "hey there i am Ayush",
    portfolio : "https://github.com/anupkgurung",
    createdAt: formatDate(),
    updatedAt: formatDate(),
  },
];
